config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'home/index'
  get 'topics/index'
  root 'home#index'
  get 'home/test'
  devise_for :users
  resources :questions #, only: [:new, :create, :edit, :update]
  resources :tests ,only: [:index, :show]
  resources :users ,only: [:index]
  resources :topics

  root to: 'questions#index'
  #get 'do_test', to: 'tests#do_test' #, as: 'tests_play_by_ques'
  get '/do_test/:id', to: 'tests#do_test', as: 'do_test'
  post '/do_test/:id', to: 'tests#show_result'

  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  patch  'setRole'  => 'users#setRole'
  patch 'setStatusTopic' => 'topics#setStatusTopic'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all , as: 'not_found'
  match "/500", :to => "errors#internal_server_error", :via => :all , as: 'internal_server_error'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy, inverse_of: :question
  has_one_attached :image
	has_one_attached :video
  has_one_attached :sound
  validate :image_validation, :video_validation, :sound_validation
  
  accepts_nested_attributes_for :answers,
    reject_if: ->(attrs) { attrs['content'].blank? || attrs['correct'].blank? }
  belongs_to :topic

  validates :content, presence: true,
          length: { minimum: 5, maximun: 1000 }
          
  def image_validation
    if image.attached?  
      if !image.blob.content_type.starts_with?('image/')
        image.purge
        errors[:base] << 'Attach file is not image'
      elsif image.blob.byte_size > 5242880
        image.purge
        errors[:base] << 'image must be less than 5 MB'
      end
    end
  end
        
  def video_validation
    if video.attached?  
      if !video.blob.content_type.starts_with?('video/')
        video.purge
        errors[:base] << 'Attach file is not video'
      elsif video.blob.byte_size > 104857600
        video.purge
        errors[:base] << 'video must be less than 100 MB'
      end
    end
  end
        
  def sound_validation
    if sound.attached?  
      if !sound.blob.content_type.starts_with?('audio/')
        sound.purge
        errors[:base] << 'Attach file is not audio'
      elsif sound.blob.byte_size > 10485760
        sound.purge
        errors[:base] << 'audio must be less than 10 MB'
      end
    end
  end
        
  def self.search(content_search, status)
    case status
    when 'all'
      if content_search
        where(['content LIKE ?', "%#{content_search}%"])
      else
        all
      end
    when 'enable'
      if content_search
        where(['content LIKE ? AND disable = ?', "%#{content_search}%", false])
      else
        where(['disable = ?', false])
      end
    when 'disable'
      if content_search
        where(['content LIKE ? AND disable = ?', "%#{content_search}%", true])
      else
        where(['disable = ?', true])
      end
    else
      all
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :only_admin

	def index
    @questions = Question.search(params[:content_search], params[:status_search]).paginate(page: params[:page], per_page: 6)
    session[:all] = params[:status_search]
    @total_number_of_question = Question.count
    @number_of_enable_question = Question.count {|question| question.disable == false}
    @number_of_disable_question = Question.count {|question| question.disable == true}
  end

  def new
    @question = Question.new(attach_type: "no_attach")
    @topics = Topic.all
    @question.answers.build
    @question.answers.build
  end

  def create
    @question = Question.new(question_params)
    # @question.topic = Topic.find_by(id: params[:question][:topic])

    case @question.attach_type
    when "image"
      @question.image.attach(params[:question][:image])
    when "sound"
      @question.sound.attach(params[:question][:sound])
    when "video"
      @question.video.attach(params[:question][:video])
    end

    if @question.save
      flash[:success] = "create successfully"
      redirect_to @question
    else
      flash[:danger] = @question.errors.full_messages.first
		  render :new
		end
  end

	def edit
    @question = Question.find_by(id: params[:id])
    @topics = Topic.all
	end

	def update
	  @question = Question.find_by(id: params[:id])
	  if @question.update_attributes(question_params)
	    redirect_to root_path
	  else
	    render :edit
	  end
  end

  def show
    @question = Question.find_by(id: params[:id])
  end

	def all_question
    @questions = Question.all
    session[:all] = 'all'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def enable_question
    @questions = Question.select {|question| question.disable == false}
    session[:all] = 'enable'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def disable_question
    @questions = Question.select {|question| question.disable == true}
    session[:all] = 'disable'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
	end
	
  def setStatus
    @question = Question.find(params[:id])
    if @question.disable == true
      @question.update(disable: false)
      @status = 'Công khai'
      @b = 'Disable'
    else
      @question.update(disable: true)
      @status = 'Vô hiệu hóa'
      @b = 'Enable'
    end

    @number_of_enable_question = Question.count {|question| question.disable == false}
    @number_of_disable_question = Question.count {|question| question.disable == true}

    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end
  
  def destroy
    @question = Question.find_by(id: params[:id])
    respond_to do |format|
      if @question.disable == false
        flash[:danger] = "Cannot delete enable question"
        format.html {redirect_to questions_path}
        # format.js {}
      else
        if @question.destroy
          flash[:success] =  'Question was successfully destroyed.' 
          format.html { redirect_to questions_path}
          format.js   {}
        else
          flash[:danger] = 'Destroy question failed.'
          format.html { redirect_to questions_path}
          format.js   {}
        end
      end
    end
  end
	
  private
	def question_params
	  params.require(:question).permit(:content, :attach_type, :question_type, :disable, :topic_id ,
	  	answers_attributes: [:id, :content, :correct, :_destroy])
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_fields.html.erb
<%if action_name == 'edit'%>
  <div class="nested-fields row row-space  pt-2 edit-answer">
<%else%>
  <div class="nested-fields row row-space  pt-2 create-answer">
<% end %>
  <div class="col-1 pt-2">
    <%= f.check_box :correct %>
  </div>
  <div class="col-10">
    <%= f.text_field :content ,class:"input--style-4 form-control" , placeholder:"Đáp án ..." ,required: true ,maxlength: "100"%>
  </div>
  <%= link_to_remove_association "<i class='fa fa-trash'></i>".html_safe, f ,class: "col-1"%>
</div>

app/views/questions/_question.html.erb
<tr>
	<td><%= question.content %></td>
	<td>
		<% if question.attach_type == "no_attach" %>
			<i class="fa fa-ban" style="font-size:20px"></i> None
		<% elsif question.attach_type == "video" %>
			<i class="fa fa-file-video-o" style="font-size:20px"></i> Video
		<% elsif question.attach_type == "sound"%>
			<i class="fa fa-file-audio-o" style="font-size:20px"></i> Mp3
		<% else %>
			<i class="fa fa-file-image-o" style="font-size:20px"></i> Image
		<% end %>
	</td>
	<td>	
	
	<% if question.disable == true %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Vô hiệu hóa</span>
		<% b = 'Enable'%>
	<% else %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Công khai</span>
		<% b = 'Disable' %>
	<% end %>
	</td>
	<td><%= question.updated_at.to_s.first(-7) %></td>
	<td>
		<%= link_to b, setStatus_path(id: question.id), method: :patch, data: { confirm: 'Are you sure?' }, 
			remote: true, class: "set-status-question", id: 'button-status-'+question.id.to_s %>
		<%= link_to 'Show', question_path(question) %>
		<%if question.disable == true %>
			<%= link_to '| Delete', question_path(question), method: :delete,
				data: { confirm: 'Are you sure?' }, class: "destroy-question" %>
		<%end%>
	</td>
	
</tr>

app/views/questions/_question_form.html.erb
<div class="card-body">
  <h2 class="title">Phần câu hỏi</h2>
  <%= form_for @question do |form| %>
    <%= form.hidden_field :question_type, value: "choose_answer" %>
    <div class="row row-space">
      <div class="col-9">
        <div class="input-group">
          <label class="label">Nội dung câu hỏi</label>
          <%= form.hidden_field :attach_type  ,value: @question.attach_type ,id: "attach_type"%>
          <%= form.text_area :content ,class:"input--style-4 form-control" ,id: "ques_content",
            placeholder: "Nội dung" ,minlength:"5" ,maxlength: "1000" ,required: true ,onkeyup: "auto_grow(this)"%>
          <div class="invalid-feedback">
              Vui lòng nhập nội dung câu hỏi.
          </div>
        </div>
        <div class="input-group row m-0 pt-3 pb-3">
          <div class="col-sm-9 p-0">
            <label class="label">Chủ đề</label>
            <%= form.select :topic_id, 
            options_for_select(@topics.map{ |s| [s.title, s.id] }, params[:topic_id]) , {} ,
            {placeholder: 'ssss',class: 'custom-select'}%>
          </div>
          <div class="col-sm-3 p-0">
            <label class="label">Độ khó</label>
            <%= form.select :difficulty, options_for_select([['Dễ', 'easy'], 
            ['Vừa', 'normal'], ['Khó', 'hard']], 'easy') , {} ,{class: 'custom-select'}%>
          </div>
        </div>
        <% case @question.attach_type %>
				<% when "images" %>
					<div class="image-preview d-flex justify-content-center"><%=image_tag @question.image %></div>
          <video controls autoplay id="video_player" class="display_none"></video>
          <audio controls id="audio_player" class="display_none"></audio>
				<% when "sound" %>
          <div class="image-preview"><img/></div>
          <video controls autoplay id="video_player" class="display_none"></video>
					<%= audio_tag rails_blob_path(@question.sound), controls: true ,id:"audio_player"%>
				<% when "video" %>
          <div class="image-preview d-flex justify-content-center "><img/></div>
					<%= video_tag rails_blob_path(@question.video), controls: true ,id:"video_player" %>
          <audio controls id="audio_player" class="display_none"></audio>
				<% when "no_attach" %>
          <div class="image-preview d-flex justify-content-center "><img/></div>
          <video controls autoplay id="video_player" class="display_none"></video>
          <audio controls id="audio_player" class="display_none"></audio>
        <% end %>
      </div>
      <div class="col-3">
        <label class="label">&nbsp;</label>
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" 
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Trắc nghiệm
          </button>
        </div>
      </div>
    </div>

    <div class="row row-space mt-2">
      <div class="col-7">
        <label class="label--inline">Đính kèm</label>
        <div class="btn-group pl-2" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="selection"><i class="fa fa-ban" style="font-size: 25px;"></i> Không</span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <li class="dropdown-item" value="0">
              <div  class="custom-file-upload" >
                <i class="fa fa-ban" style="font-size: 25px;"></i> 
                Không
              </div>
            </li>
            <li class="dropdown-item" value="1">
              <label for="image-upload" class="custom-file-upload" id="image-upload-label">
                <i class="fa fa-file-image-o" style="font-size: 25px;"></i> 
                 Hình ảnh
              </label>
            </li>
            <li class="dropdown-item" value="2">
              <label for="audio-upload" class="custom-file-upload" id="audio-upload-label">
                <i class="fa fa-file-audio-o" style="font-size: 25px;"></i>
                 Audio ngắn
              </label>
            </li>
            <li class="dropdown-item" value="3">
              <label for="video-upload" class="custom-file-upload" id="video-upload-label">
                <i class="fa fa-file-video-o" style="font-size: 25px;"></i>
                 Video ngắn
              </label>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-5">
        <div class="input-group">
          <%= form.file_field :image, class:'file--ques', accept:"image/*" ,id:"image-upload"%>
        </div>
        <div class="input-group">
          <%= form.file_field :video, class:'file--ques', accept:"video/*" ,id:"video-upload"%>
        </div>
        <div class="input-group">
          <%= form.file_field :sound, class:'file--ques', accept:"audio/*" ,id:"audio-upload"%>
        </div>
      </div>
    </div>
    <h2 class="title pt-4 mt-3">Phần câu trả lời</h2>
    <div class="row row-space">
      <div class="col-2">
        <label class="label">Đúng</label>
      </div>
      <div class="col-10">
        <label class="label">Nội dung</label>
      </div>
    </div>

    <div id="answers" class="row row-space  pt-2">
      <%= form.fields_for :answers do |answer| %>
        <%= render 'answer_fields', f: answer%>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add answer', form, :answers ,id:"add-answer"%>
      </div>
    </div>

    <%# <div class="row row-space  pt-2">
      <div class="col-1 pt-2">
        <%= form.check_box :correct1 ,class:"form-check-input css-checkbox" ,id:"correct1_check"% >
        <label for="correct1_check" class="css-label"></label>
      </div>
      <div class="col-11">
        <%= form.text_field :answer1 ,class:"input--style-4 form-control" ,
         placeholder:"Đáp án thứ nhất" ,required: true ,maxlength: "100"% >
      </div>
    </div> %>


    <% if @question.errors.messages[:base].any? %>
    <div class="row row-space  pt-2">
      <div class="col-1"></div>
      <div class="invalid-feedback display-inline col-11" >
        Vui lòng chọn đáp án đúng !
      </div>
      <div class="invalid-feedback display-inline col-11" id="invalid-file">
        Vui lòng chọn đáp án đúng !
      </div>
    </div>
    <% end %>
    <div class="row row-space  pt-2">
      <div class="col-1"></div>
      <div class="invalid-feedback display-inline col-11" id="invalid-file" 
      style="visibility: visible;"></div>
    </div>
    <%if controller_name == "questions" and action_name == "edit" %>
      <p id="index-upload" hidden>0</p>
    <% else %>
      <p id="index-upload" hidden>1</p>
    <% end %>
    <div class="row row-space  pt-4">
      <% if action_name == 'edit' %>
        <%= form.submit "UPDATE CÂU HỎI", class: "btn btn-warning", id:"submit-question-btn"%>
      <% else %>
        <%= form.submit "TẠO CÂU HỎI", class: "btn btn-warning", id:"submit-question-btn"%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/all_question.js.erb
$('#show-question').html("<%= j render @questions %>");

app/views/questions/destroy.js.erb
if (<%= @question.disable == true %>){
    $('.destroy-question').bind('ajax:success', function() {$(this).closest('tr').fadeOut();});
}

app/views/questions/edit.html.erb
<div class="page-wrapper bg-gra-02 p-b-100 font-poppins">
  <div class="wrapper wrapper--w680 pt-3 pb-4">
    <div class="card card-4">
      <div class="card-header">
        <h4>CHỈNH SỬA CÂU HỎI</h4>
      </div>
      <%= render 'question_form' %>
    </div>
  </div>
</div>

app/views/questions/enable_question.js.erb
$('#show-question').html("<%= j render @questions %>");

app/views/questions/index.html.erb
<div class="main-container container-fluid main-content pt-4">
	<section class="section home-section sevice-section text-white no-padding no-margin" id="service">
		<div class="row no-margin">
			<div class="col-md-2 left-container">
				<div class="d-flex justify-content-center  mb-3">
					<%= link_to '<i class="fa fa-pencil-square-o" style="font-size:24px"></i> THÊM CÂU HỎI'.html_safe,
					 new_question_path ,class:"btn btn-warning"%>
				</div>
				<ul class="list-group email-action">
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action active-li-item" id="all-ques-li">
						<%= link_to '<i class="fa fa-book" style="font-size:20px"></i> Tất cả'.html_safe,
						 questions_path(status_search: "all"), method: :get, remote: true ,id:"all-ques-link"%>
						<span class="badge badge-primary badge-pill"><%= @total_number_of_question %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action" id="enable-ques-li">
						<%= link_to '<i class="fa fa-globe" style="font-size:20px"></i> Công khai'.html_safe, 
						questions_path(status_search: "enable"), method: :get, remote: true ,id:"enable-ques-link"%>
						<span class="badge badge-primary badge-pill" id = "numer-enable-question"><%= @number_of_enable_question %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action" id="disable-ques-li">
						<%= link_to '<i class="fa fa-lock" style="font-size:20px" aria-hidden="true"></i> Vô hiệu hóa'.html_safe,
						 questions_path(status_search: "disable"), method: :get, remote: true ,id:"disable-ques-link"%>
						<span class="badge badge-primary badge-pill" id = "numer-disable-question"><%= @number_of_disable_question %></span>
					</li>
				</ul>
			</div>
			<div class="col-md-10 right-container">
				<div class="card">
					<div class="card-header">
						<div class="row">
							<div class="col-sm-6 col-12">
								<h2 id="title-page">BẢNG CÂU HỎI</h2>
							</div>
								<div class="col-sm-6 col-12">
									<div class="input-group">
										<%= form_tag questions_path, method: :get, remote: true, id: 'question-search', class:"form-inline my-2 my-lg-0"  do %>
											<%= text_field_tag :content_search, params[:content_search], class:"form-control", placeholder:"Nội dung tìm kiếm .." %>
											<%= select_tag :status_search, options_for_select([['all', 'all'], ['enable', 'enable'], ['disable', 'disable']], params[:status_search]) ,style: "visibility: hidden;"%>
										<% end %>
									</div> 
								</div>		
						</div>
					</div>
					<div class="card-body">
					<div id="all-mail" class="table-responsive table-body">
							<table class="table table-hover table-bordered mail-table table-striped">
								<thead class="thead-dark" id="thead-ques-index">
									<tr> 
										<th scope="col">Nội dung</th>
										<th scope="col">Đính kèm</th>
										<th scope="col">Tình trạng</th>
										<th scope="col">Edit lần cuối</th>
										<th scope="col">Chỉnh sửa</th>
									</tr>
								</thead>
								<tbody id="show-question">
									<%= render @questions %>
								</tbody>
							</table>
						<div id="show_will_paginate"><%= will_paginate @questions %></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/questions/index.js.erb
$("#show-question").html("<%= escape_javascript(render @questions) %>");
$("#show_will_paginate").html("<%= escape_javascript(will_paginate @questions) %>");

app/views/questions/new.html.erb
<div class="d-flex justify-content-center bg-gra-02 p-b-100 font-poppins row">
  <div class=" pt-3 pb-4 col-10">
    <div class="card card-4">
      <div class="card-header">
        <h2 id="title-page">TẠO CÂU HỎI</h2>
      </div>
      <%= render 'question_form' %>
    </div>
  </div>
</div>

app/views/questions/setStatus.js.erb
$('#<%='show-status-'+@question.id.to_s%>').html("<%= @status %>");
$('#<%='button-status-'+@question.id.to_s%>').text('<%= @b%>');
$('#numer-enable-question').html('<%= @number_of_enable_question %>');
$('#numer-disable-question').html('<%= @number_of_disable_question %>')
if (<%= session[:all] == 'enable' || session[:all] == 'disable' %>){
    $('#<%='button-status-'+@question.id.to_s%>').bind('ajax:success', function() {$(this).closest('tr').fadeOut();});
}

app/views/questions/show.html.erb
<div class="container mt-4">
	<div class="card">
	  <div class="card-body">
			<div class="d-flex">
				<div class="mr-auto p-2">
					<h2 id="title-page">Câu hỏi vừa khởi tạo</h2>
				</div>
				<div class="p-2">
					<p><strong>Trạng thái : </strong>
					<% if @question.disable == true %>
						<%= 'Vô hiệu hóa'%>
					<% else %>
						<%= 'Công khai' %>
					<% end %> 
					</p>
					<p><strong>Chủ đề : </strong><%= @question.topic.title %></p>
          <p><strong>Thời gian khởi tạo : </strong><%= @question.created_at %></p>
					<%= link_to 'Edit', edit_question_path(@question) %>
				</div>
			</div>
		  <hr>
      <div class="question-block mt-3"> 
        <p class="question-title">
          <strong>Câu hỏi: </strong>
          <%= @question.content %>
        </p>
        <% case @question.attach_type %>
        <% when "image" %>
        <div class="d-flex justify-content-center pb-3">	
          <%= image_tag @question.image ,class:"ques-test-img"%> 
        </div>
        <% when "sound" %>
          <%= audio_tag rails_blob_path(@question.sound), controls: true %>
        <% when "video" %>
          <%= video_tag rails_blob_path(@question.video), controls: true %>
        <% end %>
        <div class="answer-block" data-question-type="multi_choice">
          <div class="question-form" > 
            <% @question.answers.each do |answer| %>
              <%if answer.correct %>
                <div class="s_question_selection checked_border right_checked_border d-flex">
                  <span class="choice-index-span">
                    <code><%= answer.content %></code>
                  </span>
                </div>
              <% else %>
                <div class="s_question_selection checked_border no_checked_border d-flex">
                  <span class="choice-index-span">
                    <code><%= answer.content %></code>
                  </span>
                </div>
              <% end %> 
            <% end %>
          </div>
        </div>
      </div>
			<hr>
			<div class="d-flex justify-content-center">

			</div>
	  </div>
	</div>
</div>