config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'home/index'
  get 'topics/index'
  root 'home#index'
  get 'home/test'
  devise_for :users
  resources :questions #, only: [:new, :create, :edit, :update]
  resources :tests ,only: [:index, :show]
  resources :users ,only: [:index]
  resources :topics

  root to: 'questions#index'
  #get 'do_test', to: 'tests#do_test' #, as: 'tests_play_by_ques'
  get '/do_test/:id', to: 'tests#do_test', as: 'do_test'
  post '/do_test/:id', to: 'tests#show_result'

  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  patch  'setRole'  => 'users#setRole'
  patch 'setStatusTopic' => 'topics#setStatusTopic'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all , as: 'not_found'
  match "/500", :to => "errors#internal_server_error", :via => :all , as: 'internal_server_error'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions
  has_many :tests

  validates :title, presence: true,
					length: { minimum: 5, maximun: 1000 }
					
	# validate :number_of_question, 
          
  def self.search(topic_search)
    case topic_search
		when 'all'
			all
		when 'enable'
			where(['disable = ?', false])
		when 'disable'
			where(['disable = ?', true])
		else
			all
		end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :only_admin

  def index
    @topics = Topic.search(params[:topic_search]).paginate(page: params[:page], per_page: 6)
    @number_all = Topic.count
    @number_enable = Topic.count{|topic| topic.disable == false}
    @number_disable = @number_all - @number_enable
    session[:present_tab] = params[:topic_search]
  end

  def create
    @topic = Topic.new(create_topic_params)

    respond_to do |format|
      if @topic.save
        @number_all = Topic.count
        @number_enable = Topic.count{|topic| topic.disable == false}
        format.html {redirect_to topics_path}
        format.js {}
      else
        flash[:danger] = @topic.errors.full_messages.first
        format.html {redirect_to topics_path}
      end
    end
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    @questions = @topic.questions.paginate(page: params[:page], per_page: 6)
  end

  def edit
    @topic = Topic.find_by(id: params[:id])
  end

  def update
    @topic = Topic.find_by(id: params[:id])
    p 2,3,3,4,5,params

    respond_to do |format|
      if @topic.update(update_topic_params)
        format.html {redirect_to topics_path}
        format.js {}
      else
        flash[:danger] = @topic.errors.full_messages.first
        format.html {redirect_to topics_path}
      end
    end
  end

  def setStatusTopic
    @topic = Topic.find_by(id: params[:id])
    if @topic.disable == true
      @topic.update(disable: false)
      @topic_status = 'Công khai'
      @b = "Disable"
    else
      @topic.update(disable: true)
      @topic_status = 'Vô hiệu hóa'
      @b = "Enable"
    end

    @number_enable = Topic.count{|topic| topic.disable == false}
    @number_disable = Topic.count{|topic| topic.disable == true}

    respond_to do |format|
      format.html {redirect_to topics_path}
      format.js {}
    end
	end

  def create_topic_params
    params.require(:topic).permit(:title , :number_of_question ,:topic_time)
  end

  def update_topic_params
    params[:topic][:topic_time] = params[:topic][:topic_time].to_i * 60
    params.require(:topic).permit(:title, :disable, :number_of_question ,:topic_time )
  end

  def setStatus
    @topic = Topic.find_by(id: params[:id])
    @topic.update(disable: !(@topic.disable))
    @b = @topic.disable.to_s
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_edit_topic.html.erb
<%= form_with model: @topic do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_area :title %>
   </p>

   <p>
      <%= form.label :disable %><br>
      <%= form.select :disable, options_for_select([['true', true], ['false', false]], @topic.disable) %>
   </p>

   <p>
      <%= form.label :number_of_question %><br>
      <%= form.text_field :number_of_question %>
   </p>
    
    <p>
      <%= form.submit%>
    </p>
<% end %>

app/views/topics/_new_topic.html.erb
<%= form_with scope: :topic, url: topics_path do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_area :title %>
   </p>
    
    <p>
      <%= form.submit%>
    </p>
<% end %>

app/views/topics/_question.html.erb
<tr>
	<td><%= question.content %></td>
	<td>
		<% if question.attach_type == "no_attach" %>
			<i class="fa fa-ban" style="font-size:20px"></i> None
		<% elsif question.attach_type == "video" %>
			<i class="fa fa-file-video-o" style="font-size:20px"></i> Video
		<% elsif question.attach_type == "sound"%>
			<i class="fa fa-file-audio-o" style="font-size:20px"></i> Mp3
		<% else %>
			<i class="fa fa-file-image-o" style="font-size:20px"></i> Image
		<% end %>
	</td>
	<td>	
	<% if question.disable == true %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Vô hiệu hóa</span>
		<% b = 'Enable'%>
	<% else %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Công khai</span>
		<% b = 'Disable' %>
	<% end %>
	</td>
	<td><%= question.updated_at.to_s.first(-7) %></td>
	<td>
		<%= link_to b, setStatus_path(id: question.id), method: :patch, data: { confirm: 'Are you sure?' }, 
			remote: true, class: "set-status-question", id: 'button-status-'+question.id.to_s %>
		<%= link_to 'Show', question_path(question) %>
	</td>
</tr>

app/views/topics/_topic.html.erb
<tr id=<%='topic-'+topic.id.to_s%>>
	<td><%= topic.title %></td>
	<td><%= topic.number_of_question %></td>
	<td>	
	<% if topic.disable == true %>
		<span id = '<%='show-status-'+topic.id.to_s%>'>Vô hiệu hóa</span>
		<% b = 'Enable'%>
	<% else %>
		<span id = '<%='show-status-'+topic.id.to_s%>'>Công khai</span>
		<% b = 'Disable' %>
	<% end %>
	</td>
	<td><%= topic.questions.size %></td>
	<td><%= topic.topic_time / 60 %></td>
	<td>
		<%= link_to "Show", topic_path(topic) %>
    <%= link_to b, setStatusTopic_path(id: topic.id), method: :patch, data: { confirm: 'Are you sure?' }, remote: true, id: 'button-status-'+topic.id.to_s %>
	</td>
</tr>

app/views/topics/create.js.erb
$("<%= escape_javascript(render @topic) %>").appendTo("#show_all_topics");
$('#number-all-topic').html('<%= @number_all %>');
$('#number-enable-topic').html('<%= @number_enable %>');
$('#createTopicModal').modal('toggle');

app/views/topics/index.html.erb
<div class="main-container container-fluid main-content pt-4">
	<section class="section home-section sevice-section text-white no-padding no-margin" id="service">
		<div class="row no-margin">
			<div class="col-md-2 left-container">
				<div class="d-flex justify-content-center  mb-3">
					<button type="button" class="btn" data-toggle="modal" 
						data-target="#createTopicModal" style="background-color: #e98a00;" >
						<i class="fa fa-pencil-square" style="font-size:24px"></i> THÊM CHỦ ĐỀ
					</button>
				</div>
				<ul class="list-group email-action">
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action active-li-item" id="all-ques-li">
						<%= link_to '<i class="fa fa-book" style="font-size:20px"></i> Tất cả'.html_safe,
						 topics_path(topic_search: "all"), method: :get, remote: true ,id:"all-ques-link"%>
						<span class="badge badge-primary badge-pill" id = "number-all-topic"><%= @number_all %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action" id="enable-ques-li">
						<%= link_to '<i class="fa fa-globe" style="font-size:20px"></i> Công khai'.html_safe, 
						topics_path(topic_search: "enable"), method: :get, remote: true ,id:"enable-ques-link"%>
						<span class="badge badge-primary badge-pill" id = "number-enable-topic"><%= @number_enable %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action" id="disable-ques-li">
						<%= link_to '<i class="fa fa-lock" style="font-size:20px" aria-hidden="true"></i> Vô hiệu hóa'.html_safe,
						 topics_path(topic_search: "disable"), method: :get, remote: true ,id:"disable-ques-link"%>
						<span class="badge badge-primary badge-pill" id = "number-disable-topic"><%= @number_disable %></span>
					</li>
				</ul>
			</div>
			<div class="col-md-10 right-container">
				<div class="card">
					<div class="card-header">
						<div class="row">
							<div class="col-sm-6">
								<h2 id="title-page">BẢNG CHỦ ĐỀ</h2>
							</div>
								<div class="col-sm-6 ">
									<div class="input-group">

									</div> 
								</div>		
						</div>
					</div>
					<div class="card-body">
						
						<div id="all-mail" class="table-responsive table-body">
								<table class="table table-hover table-bordered mail-table table-striped">
								<thead class="thead-dark">
									<tr> 
										<th scope="col">Tên</th>
										<th scope="col">Số câu hỏi phải làm</th>
										<th scope="col">Tình trạng</th>
										<th scope="col">Tổng số câu hỏi hiện có</th>
										<th scope="col">Thời gian làm bài (phút)</th>
										<th scope="col">Chỉnh sửa</th>
									</tr>
								</thead>
								<tbody id="show_all_topics">
                  <%= render @topics %>
								</tbody>
							</table>
						<div id="show_will_paginate"><%= will_paginate @topics %></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
										
<div class="modal fade" id="createTopicModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tạo mới chủ đề :</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
			<%= form_with scope: :topic, url: topics_path do |form| %>
				<div class="modal-body">
					<div class="form-group">
						<label for="title-name" class="col-form-label"><b>Chủ đề : </b></label>
						<%= form.text_field :title ,class:"form-control" ,id:"title-name" ,required: true,minlength:"5"%>
					</div>
					<div class="form-group">
						<label for="num-ques-name" class="col-form-label"><b>Số câu hỏi mặc định :</b></label>
						<%= form.number_field :number_of_question ,class:"form-control" ,id:"num-ques-name",required: true ,min: 5 ,max: 30%>
					</div>
					<div class="form-group">
						<label for="topic-time" class="col-form-label"><b>Thời gian làm bài :</b></label>
						<div class="input-group">
							<input type="number" class="form-control" aria-describedby="basic-addon2"
							id="topic-time" name="topic[topic_time]" min="5" max="60" required>
							<div class="input-group-append">
								<span class="input-group-text" id="basic-addon2">phút</span>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
					<%= form.submit "THÊM CHỦ ĐỀ",class:"btn btn-primary" %>
				</div>
			<% end %>
    </div>
  </div>
</div>

app/views/topics/index.js.erb
$("#show_all_topics").html("<%= escape_javascript(render @topics) %>");
$("#show_will_paginate").html("<%= escape_javascript(will_paginate @topics) %>");

app/views/topics/setStatusTopic.js.erb
$('#<%='show-status-'+@topic.id.to_s%>').html("<%= @topic_status %>");
$('#<%='button-status-'+@topic.id.to_s%>').text('<%= @b%>');
$('#number-enable-topic').html('<%= @number_enable %>');
$('#number-disable-topic').html('<%= @number_disable %>');
if (<%= session[:present_tab] == 'enable' || session[:present_tab] == 'disable' %>){
    $('#<%='button-status-'+@topic.id.to_s%>').bind('ajax:success', function() {$(this).closest('tr').fadeOut();});
}

app/views/topics/show.html.erb
<div class="container mt-4">
	<div class="card">
	  <div class="card-body">
			<div class="d-flex">
				<div class="mr-auto p-2">
					<h2 id="title-page"><%= @topic.title %></h2>
					<button type="button" class="btn btn-info" data-toggle="modal" 
					data-target="#exampleModal" >Chỉnh sửa</button>
					<%= link_to "Tạo câu hỏi", new_question_path(topic_id: @topic.id), role:"button", class:"btn btn-warning" %>
				</div>
				<div class="">
					<p>
						<strong>Số câu hỏi mặc định: </strong>
						<span id="topic-number"><%= @topic.number_of_question %></span>
					</p>
		  		<p>
						<strong>Thời gian làm bài : </strong>
						<span id="topic_time"><%= @topic.topic_time / 60 %> phút</span>
					</p>
		  		<p>
						<strong>Tổng số câu hỏi hiện có : </strong>
						<span id="ques-number"><%= @topic.questions.size %></span>
					</p>
		  		<p>
						<strong>Thời gian khởi tạo : </strong>
						<span id="topic-created-at"><%= @topic.created_at.to_s.first(-7) %></span>
					</p>
				</div>
			</div>
		  <hr>
	  <div class="question-block mt-3 table-responsive table-body"> 
			<table class="table table-hover table-bordered mail-table table-striped">
				<thead class="thead-dark">
					<tr> 
						<th scope="col">Nội dung</th>
						<th scope="col">Đính kèm</th>
						<th scope="col">Tình trạng</th>
						<th scope="col">Edit lần cuối</th>
						<th scope="col">Chỉnh sửa</th>
					</tr>
				</thead>
				<tbody id="show-question">
					<%= render @questions %>
				</tbody>
			</table>
		<div id="show_will_paginate"><%= will_paginate @questions %></div>
	  </div>
			<hr>
			<div class="d-flex justify-content-center">

			</div>
	  </div>
	</div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cập nhật thông tin chủ đề :</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
			<%= form_with model: @topic do |form| %>
				<div class="modal-body">
					<div class="form-group">
						<label for="title-name" class="col-form-label"><b>Chủ đề : </b></label>
						<%= form.text_field :title ,class:"form-control" ,id:"title-name" ,required: true,minlength:"5"%>
					</div>
					<div class="form-group">
						<label for="num-ques-name" class="col-form-label"><b>Số câu hỏi mặc định :</b></label>
						<%= form.number_field :number_of_question ,class:"form-control" ,id:"num-ques-name" ,required: true ,min: 5 ,max: 30%>
					</div>
					<div class="form-group">
						<label for="topic-time" class="col-form-label"><b>Thời gian làm bài :</b></label>
						<div class="input-group">
							<input type="number" class="form-control" aria-describedby="basic-addon2"
							id="topic-time" name="topic[topic_time]" min="5" max="60" required value="<%= @topic.topic_time / 60 %>">
							<div class="input-group-append">
								<span class="input-group-text" id="basic-addon2">phút</span>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<%= form.submit "Update",class:"btn btn-primary" %>
				</div>
			<% end %>
    </div>
  </div>
</div>

app/views/topics/update.js.erb
$('#title-page').text('<%= @topic.title %>');
$('#topic-number').text('<%= @topic.number_of_question %>');
$('#topic_time').text('<%= @topic.topic_time / 60 %> phút');
$('#topic-created-at').text('<%= @topic.created_at.to_s.first(-7) %>');
$('#exampleModal').modal('toggle');