config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'home/index'
  get 'topics/index'
  root 'home#index'
  get 'home/test'
  devise_for :users
  resources :questions #, only: [:new, :create, :edit, :update]
  resources :tests ,only: [:index, :show]
  resources :users ,only: [:index]
  resources :topics

  root to: 'questions#index'
  #get 'do_test', to: 'tests#do_test' #, as: 'tests_play_by_ques'
  get '/do_test/:id', to: 'tests#do_test', as: 'do_test'
  post '/do_test/:id', to: 'tests#show_result'

  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  patch  'setRole'  => 'users#setRole'
  patch 'setStatusTopic' => 'topics#setStatusTopic'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all , as: 'not_found'
  match "/500", :to => "errors#internal_server_error", :via => :all , as: 'internal_server_error'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @topics = Topic.where(disable: false)
    @topics.each do |value|
      if value.number_of_question > value.questions.size
        @topics = @topics.reject{|x| x ==value}
      end
    end
  end

  def test
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_user_index.html.erb
<div class="pt-4 d-flex justify-content-center">
	<div class="container">
	 	<div class="row">
			<% @topics.each do |topic| %>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="box-part text-center">
						<div class="title">
							<h3><%= topic.title %></h3>
						</div>
						<div class="text">
							<span>Số câu hỏi : <%= topic.number_of_question %></span>
						</div>
						<div class="text">
							<span>Thời gian làm bài : <%= topic.topic_time / 60 %> phút</span>
						</div>
						<%= link_to 'Làm bài', do_test_path(topic) %>
					</div>
				</div>
			<% end %>
		</div>		
	</div>
</div>

app/views/home/index.html.erb
<% if current_user.role == 'admin' %>
	<% controller.redirect_to topics_path %>
<% else %>
	<%= render 'user_index' %>
<% end %>

app/views/home/test.html.erb
<link rel="stylesheet" href="svgTimer.min.css">
<script src="//code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<script src="svgTimer.min.js"></script>