config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'home/index'
  get 'topics/index'
  root 'home#index'
  get 'home/test'
  devise_for :users
  resources :questions #, only: [:new, :create, :edit, :update]
  resources :tests ,only: [:index, :show]
  resources :users ,only: [:index]
  resources :topics

  root to: 'questions#index'
  #get 'do_test', to: 'tests#do_test' #, as: 'tests_play_by_ques'
  get '/do_test/:id', to: 'tests#do_test', as: 'do_test'
  post '/do_test/:id', to: 'tests#show_result'

  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  patch  'setRole'  => 'users#setRole'
  patch 'setStatusTopic' => 'topics#setStatusTopic'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all , as: 'not_found'
  match "/500", :to => "errors#internal_server_error", :via => :all , as: 'internal_server_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizAgain</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="<%= controller_name %> <%= action_name %>">
	<nav class="navbar navbar-expand-lg navbar-dark">
	  <a class="navbar-brand" href="<%= root_path %>">
    <%= fa_stacked_icon "question-circle"%>ADMIN</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <% if user_signed_in? && current_user.role == 'admin' %>
          <li class="nav-item">
            <%= link_to 'CHỦ ĐỀ', topics_path, class:"nav-link" ,id:"topic_link"%>
	        </li>
	        <li class="nav-item">
            <%= link_to 'CÂU HỎI', questions_path, class:"nav-link" ,id:"home_link"%>
	        </li>
	        <li class="nav-item">
            <%= link_to 'BÀI TEST', tests_path, class:"nav-link" ,id:"test_link"%>
	        </li>
	        <li class="nav-item">
            <%= link_to 'TÀI KHOẢN', users_path, class:"nav-link" ,id:"user_link"%>
	        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'TRANG CHỦ', root_path, class:"nav-link" ,id:"home_link"%>
	        </li>
          <li class="nav-item">
            <%= link_to 'BÀI TEST', tests_path, class:"nav-link" ,id:"test_link"%>
	        </li>
        <% end %>
	    </ul>
	    <form class="form-inline my-2 my-lg-0 nav_user">
        <% if user_signed_in? %>
          <span>Hello <%= current_user.email %></span>
          <a href= "<%= edit_user_registration_path(current_user)%>" class ="pl-3">
            <i class='fa fa-user nav_icon'></i> Edit profile
          </a>
          <a href="<%= destroy_user_session_path%>" data-method="delete" class ="pl-3">
            <i class="fa fa-sign-out nav_icon"></i> Logout
          </a>
        <% else %>
          <a href='<%= new_user_session_path%>' class ="pl-3">
            <i class='fa fa-sign-in nav_icon'></i> Login
          </a>
          <a href='<%= new_user_registration_path%>' class ="pl-3">
            <i class="fas fa-user-plus nav_icon"></i> Sign up
          </a>           
        <% end %>
	      
	    </form>
	  </div>
	</nav>

  <div class="container">
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
  </div>
    <script>
      $(".alert" ).fadeOut(3000);
    </script>


  <!--<p class="notice"><%= notice %></p>
  <p class="notice"><%= alert %></p>-->
  
    <%= yield %>
</body>
</html>